<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXUuWAZ2\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXUuWAZ2/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXUuWAZ2.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXUuWAZ2\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXUuWAZ2\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XUuWAZ2',
    'container.build_id' => '81ff4314',
    'container.build_time' => 1543412774,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXUuWAZ2');
